apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inference-server
spec:
  type: {{ .Values.service.type }}
  selector:
    app: inference-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
