image:
  pullPolicy: Never
  repository: llm-inference-server
  tag: v2.2
mlflow:
  s3EndpointUrl: http://host.docker.internal:9000
  trackingUri: http://host.docker.internal:5001
model:
  name: llm-chatbot
  stage: Production
  version: '2'
replicaCount: 1
resources:
  limits:
    cpu: 2000m
    memory: 3Gi
  requests:
    cpu: 500m
    memory: 1Gi
service:
  nodePort: 30800
  port: 8000
  type: NodePort
